### ISSUE TITLE
[PE-D] Description cannot contain by/ or at/

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-1/tp#200]
![image.png](https://raw.githubusercontent.com/vishandi/ped/master/files/df2ca8c4-ab66-4bf1-b9e2-6fd1c0ef4d2c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: vishandi/ped#6

**Comment by alfredkohhh** [comment]
![image](https://user-images.githubusercontent.com/70746290/161494335-99cfc011-8c3d-41ae-bab4-2aaf50d48edf.png)

Started with a fresh ManageEZPZ.jar, unable to replicate the bug stated in the issue.
