### ISSUE TITLE
[PE-D] Suggested Improvement in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-1/tp#232]
![image.png](https://raw.githubusercontent.com/vishandi/ped/master/files/5c15c5dc-f9eb-4149-ad8e-e4d79ead3c17.png)

This part someone could say that chaining options is not allowed since it is not stated in the format.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: vishandi/ped#20

**Comment by alfredkohhh** [comment]
![image](https://user-images.githubusercontent.com/70746290/161530004-dd3fc38c-a17b-4103-ac39-98e2a7627e18.png)
Our team has written examples to show that the findTask command is able to chain as intended. Will close.
